# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  create

jobs:
  new_branch:
    runs-on: ubuntu-latest
  
    steps:
      - uses: goshencollege/validate-branch-name@v1.0.1
        with:
          pattern: "^[a-z-]+$"
        
