# This is a basic workflow to help you get started with Actions

name: Check Branch Name

# Controls when the workflow will run
on:
  create

jobs:

  new_branch:
    
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: check-branch
        run: echo 'Yep thats a branch name'
        
